# Generated by Django 5.0.3 on 2024-05-25 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='relacao',
            name='nome',
        ),
        migrations.AddField(
            model_name='relacao',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_app.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacao',
            name='qtd_adulto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacao',
            name='qtd_bebe',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacao',
            name='qtd_crianca',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacao',
            name='qtd_pet',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
